-- MySQL Script generated by MySQL Workbench
-- Sun Apr 20 15:30:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `Grupo24_OO2` DEFAULT CHARACTER SET utf8 ;
USE `Grupo24_OO2` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grupo24_OO2`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `dni` INT NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `fechaDeNacimiento` DATE NOT NULL,
  `baja` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grupo24_OO2`.`Contacto` (
  `telefono` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `idContacto` INT NOT NULL,
  PRIMARY KEY (`idContacto`),
  INDEX `fk_Contacto_Usuario_idx` (`idContacto` ASC) VISIBLE,
  CONSTRAINT `fk_Contacto_Usuario`
    FOREIGN KEY (`idContacto`)
    REFERENCES `Grupo24_OO2`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grupo24_OO2`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `fechaDeIngreso` DATE NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleado_Usuario1_idx` (`idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Usuario1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `Grupo24_OO2`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsuarioFinal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grupo24_OO2`.`UsuarioFinal` (
  `idUsuarioFinal` INT NOT NULL,
  PRIMARY KEY (`idUsuarioFinal`),
  CONSTRAINT `fk_UsuarioFinal_Usuario1`
    FOREIGN KEY (`idUsuarioFinal`)
    REFERENCES `Grupo24_OO2`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grupo24_OO2`.`Ticket` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `fechaDeCreacion` DATE NOT NULL,
  `usuarioFinal` INT NOT NULL,
  PRIMARY KEY (`idTicket`),
  INDEX `fk_Ticket_UsuarioFinal1_idx` (`usuarioFinal` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_UsuarioFinal1`
    FOREIGN KEY (`usuarioFinal`)
    REFERENCES `Grupo24_OO2`.`UsuarioFinal` (`idUsuarioFinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grupo24_OO2`.`Estado` (
  `idEstado` INT NOT NULL,
  `tipoDeEstado` ENUM('enviado', 'recibido', 'finalizado') NOT NULL DEFAULT 'enviado',
  `descripcionDelEstado` VARCHAR(300) NOT NULL,
  `ultimoCambioEstado` DATETIME NOT NULL,
  PRIMARY KEY (`idEstado`),
  CONSTRAINT `fk_Estado_Ticket1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `Grupo24_OO2`.`Ticket` (`idTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TicketTieneEmpleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grupo24_OO2`.`TicketTieneEmpleado` (
  `idTicket` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTicket`, `idUsuario`),
  INDEX `fk_Ticket_has_Empleado_Empleado1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Ticket_has_Empleado_Ticket1_idx` (`idTicket` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_has_Empleado_Ticket1`
    FOREIGN KEY (`idTicket`)
    REFERENCES `Grupo24_OO2`.`Ticket` (`idTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_has_Empleado_Empleado1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Grupo24_OO2`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
